apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: tms
  labels:
    app: sample-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/successCodes: '200'
spec:
  ports:
    - port: 8080
  selector:
    app: sample-service
    version: "0.0.1"
  type: NodePort