apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: tms
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-tms
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-953bfcd5